### ISSUE TITLE
Enable read permission on `/var/log/unit/*` for ezid group

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/N2T#24]
Unitd for N2T is configured to write an access log to `/var/log/unit/access.log`.

This log file should be readable by the ezid user for diagnostic purposes (actually any of the unit logs should be readable by ezid). Task here is to set permissions so that existing and new (e.g. from log rotation) files are readable by the ezid user or group.

**Comment by ashleygould** [comment]
This permission is already incorporated in puppet managed logrotate configuration.  When I provission n2t service, I will touch the access.log and chmod all unit logs so that ezid has read access at initial startup.
