### ISSUE TITLE
DNS cutover for n2t.net

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/N2T#30]
N2T Production
-----------------------

We want the domain names listed below to resolve to
`uc3-ezidn2t-prd-alb-654036320.us-west-2.elb.amazonaws.com`, which is the DNS
name for ALB `uc3-ezidn2t-prd-alb`.  Whether to use Route53 Alias or CNAME is
up to IAS to decide.
  
- n2t.net
- www.n2t.net
- n2t.org
- www.n2t.org
- n2t.info
- www.n2t.info

The n2t.net DNS domain is hosted in AWS Route53 as both a public hostedzone and
private hostedzone, so dns changes must be made in both.  In addition, there
are also Route53 public hostedzones for domains `n2t.org` and `n2t.info`.
  
  
#### Current configuration

Public hostedzone for n2t.net.
```
{ 
  "Name": "n2t.net.",
  "Type": "A",
  "AliasTarget": {

    "HostedZoneId": "Z2S3PX4140ZOHT",
    "DNSName": "ids-n2t2-prd.n2t.net.",
    "EvaluateTargetHealth": false
  }
}
{
  "Name": "www.n2t.net.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "n2t.net"
    }
  ]
}   
```

Private hostedzone for n2t.net.
```
{ 
  "Name": "n2t.net.",
  "Type": "A",
  "AliasTarget": {
    "HostedZoneId": "Z1RGJCUDYX3TCI",
    "DNSName": "ids-n2t2-prd.n2t.net.",
    "EvaluateTargetHealth": false
  }
}
{
  "Name": "www.n2t.net.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "n2t.net"
    }
  ]
}
```

Hostedzone for n2t.org.
```
{
  "Name": "n2t.org.",
  "Type": "A",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "54.244.52.1"
    }
  ]
}
{
  "Name": "www.n2t.org.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "n2t.net"
    }
  ]
}
```

Hostedzone for n2t.info.
```
{
  "Name": "n2t.info.",
  "Type": "A",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "54.244.52.1"
    }
  ]
}
{
  "Name": "www.n2t.info.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "n2t.net"
    }
  ]
}
```

---

N2T Stage
-----------

For stage there is only one domain to update - `n2t-stg.n2t.net`.

We want `n2t-stg.n2t.net` to resolve to
`uc3-ezidn2t-stg-alb-375312303.us-west-2.elb.amazonaws.com`, which is the DNS
name for ALB `uc3-ezidn2t-stg-alb`.  I assume IAS will use Route53 Alias for these.

#### Current configuration
```
agould@uc3-aws2-ops:~> route53-recordset-show  n2t.net n2t-stg.n2t.net.
Public Hosted Zone:
{
  "Name": "n2t-stg.n2t.net.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "ids-n2t2-stg.n2t.net"
    }
  ]
}

Private Hosted Zone:
{
  "Name": "n2t-stg.n2t.net.",
  "Type": "CNAME",
  "TTL": 300,
  "ResourceRecords": [
    {
      "Value": "ids-n2t2-stg.n2t.net"
    }
  ]
}
``

**Comment by marisastrong** [comment]
Do we have test cases for the DNS cutover?

**Comment by jsjiang** [comment]
Note: schedule with IAS a day before the cutover day

**Comment by jsjiang** [comment]
> Have we identified test cases for the DNS cutover?
1. check with the `nslookup` command
2. Check log files on the new and old server
3. Other?

**Comment by datadavev** [comment]
Completed.
